# Generated by Django 4.1.7 on 2023-03-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0009_company_rename_childuser_companyemployer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colorCode', models.TextField()),
                ('colorName', models.TextField()),
                ('brand', models.TextField()),
                ('material', models.CharField(default='PAL', max_length=20)),
                ('dimensionHeight', models.IntegerField(default=2800)),
                ('dimensionLength', models.IntegerField(default=2070)),
                ('dimensionWidth', models.IntegerField(default=18)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.TextField(default='appAdmin')),
            ],
            options={
                'ordering': ['id', 'brand', 'material', 'colorCode'],
                'unique_together': {('colorCode', 'brand', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colorCode', models.TextField()),
                ('brand', models.TextField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('colorName', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.TextField(default='appAdmin')),
            ],
            options={
                'ordering': ['id', 'colorCode', 'length', 'width'],
                'unique_together': {('colorCode', 'brand', 'length', 'width')},
            },
        ),
        migrations.CreateModel(
            name='StockEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noMeters', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.companyemployer')),
                ('idEdge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.edge')),
            ],
            options={
                'ordering': ['companyName', 'idEdge'],
                'unique_together': {('companyName', 'idEdge')},
            },
        ),
        migrations.CreateModel(
            name='StockBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noPieces', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.companyemployer')),
                ('idBoard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.board')),
            ],
            options={
                'ordering': ['companyName', 'idBoard'],
                'unique_together': {('companyName', 'idBoard')},
            },
        ),
    ]
