# Generated by Django 4.1.7 on 2023-02-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0007_alter_stockboard_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colorCode', models.TextField()),
                ('colorName', models.TextField()),
                ('brand', models.TextField()),
                ('material', models.CharField(default='PAL', max_length=20)),
                ('dimensionHeight', models.IntegerField(default=2800)),
                ('dimensionLength', models.IntegerField(default=2070)),
                ('dimensionWidth', models.IntegerField(default=18)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['brand', 'material', 'colorCode'],
                'unique_together': {('colorCode', 'brand', 'material')},
            },
        ),
        migrations.CreateModel(
            name='StockBoard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('noPieces', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('colorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.board')),
                ('companyEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.userdetails')),
            ],
            options={
                'ordering': ['companyEmail', 'colorCode'],
                'unique_together': {('companyEmail', 'colorCode')},
            },
        ),
    ]
