# Generated by Django 4.1.7 on 2023-03-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='edge',
            name='author',
            field=models.TextField(),
        ),
    ]
