# Generated by Django 4.1.7 on 2023-03-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0011_alter_companyemployer_middlename_and_more'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colorCode', models.TextField()),
                ('colorName', models.TextField()),
                ('brand', models.TextField()),
                ('material', models.CharField(max_length=20)),
                ('height', models.IntegerField(default=1000)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.TextField()),
            ],
            options={
                'ordering': ['id', 'brand', 'material', 'colorCode', 'length', 'width'],
                'unique_together': {('colorCode', 'brand', 'material', 'length', 'width')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noPieces', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('companyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.company')),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.material')),
            ],
            options={
                'ordering': ['id', 'companyName', 'idMaterial'],
                'unique_together': {('companyName', 'idMaterial')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='stockboard',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockboard',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='stockboard',
            name='idBoard',
        ),
        migrations.AlterUniqueTogether(
            name='stockedge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockedge',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='stockedge',
            name='idEdge',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='StockBoard',
        ),
        migrations.DeleteModel(
            name='StockEdge',
        ),
    ]
