# Generated by Django 4.1.7 on 2023-03-04 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_alter_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockboard',
            name='companyEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
