# Generated by Django 4.1.7 on 2023-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stockboard_companyemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='dimensionHeight',
            field=models.IntegerField(blank=True, default=2800, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='dimensionLength',
            field=models.IntegerField(blank=True, default=2070, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='dimensionWidth',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
