# Generated by Django 4.1.7 on 2023-03-16 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0011_alter_companyemployer_middlename_and_more'),
        ('stocks', '0006_alter_stockboard_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockboard',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.companyemployer'),
        ),
    ]
