# Generated by Django 4.1.7 on 2023-03-09 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0006_alter_board_dimensionheight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colorCode', models.TextField()),
                ('brand', models.TextField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('colorName', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['colorCode', 'length', 'width'],
                'unique_together': {('colorCode', 'brand', 'length', 'width')},
            },
        ),
        migrations.AlterModelOptions(
            name='stockboard',
            options={'ordering': ['companyEmail', 'idBoard']},
        ),
        migrations.RenameField(
            model_name='stockboard',
            old_name='colorCode',
            new_name='idBoard',
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='stockboard',
            unique_together={('companyEmail', 'idBoard')},
        ),
        migrations.CreateModel(
            name='StockEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noMeters', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('companyEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idEdge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.edge')),
            ],
            options={
                'ordering': ['companyEmail', 'idEdge'],
                'unique_together': {('companyEmail', 'idEdge')},
            },
        ),
    ]
