# Generated by Django 4.1.7 on 2023-03-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_edge_alter_stockboard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id', 'brand', 'material', 'colorCode']},
        ),
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ['id', 'colorCode', 'length', 'width']},
        ),
    ]
