# Generated by Django 4.1.7 on 2023-02-21 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.TextField()),
                ('middleName', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('adress', models.TextField()),
                ('phone', models.IntegerField()),
                ('company', models.TextField()),
                ('accountType', models.TextField()),
                ('accountPermisions', models.TextField(default='admin')),
            ],
        ),
    ]
