# Generated by Django 4.1.7 on 2023-02-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('colorCode', models.TextField(primary_key=True, serialize=False)),
                ('colorName', models.TextField()),
                ('brand', models.TextField()),
                ('material', models.TextField()),
                ('dimensionHeight', models.IntegerField(default=2800)),
                ('dimensionLength', models.IntegerField(default=2070)),
                ('dimensionWidth', models.IntegerField(default=18)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['brand', 'material', 'colorCode'],
                'unique_together': {('colorCode', 'brand', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('colorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.materials')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.userdetails')),
            ],
            options={
                'ordering': ['company', 'colorCode'],
                'unique_together': {('company', 'colorCode')},
            },
        ),
    ]
