# Generated by Django 4.1.7 on 2023-02-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_materials_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='amount',
            new_name='noPieces',
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colorCode', models.TextField()),
                ('colorName', models.TextField()),
                ('brand', models.TextField()),
                ('material', models.CharField(default='PAL', max_length=20)),
                ('dimensionHeight', models.IntegerField(default=2800)),
                ('dimensionLength', models.IntegerField(default=2070)),
                ('dimensionWidth', models.IntegerField(default=18)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['brand', 'material', 'colorCode'],
                'unique_together': {('colorCode', 'brand', 'material')},
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='colorCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.board'),
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
