# Generated by Django 4.1.7 on 2023-02-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_alter_userdetails_accountpermisions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['companyEmail', 'colorCode']},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='company',
            new_name='companyEmail',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('companyEmail', 'colorCode')},
        ),
    ]
