# Generated by Django 4.1.7 on 2023-02-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0005_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockBoard',
        ),
    ]
