# Generated by Django 4.1.7 on 2023-02-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0006_rename_stock_stockboard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockboard',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockboard',
            name='colorCode',
        ),
        migrations.RemoveField(
            model_name='stockboard',
            name='companyEmail',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='StockBoard',
        ),
    ]
