# Generated by Django 4.1.7 on 2023-03-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userAuth', '0007_alter_stockboard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='company',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='ChildUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.TextField()),
                ('middleName', models.TextField()),
                ('accountPermisions', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.userdetails')),
            ],
        ),
    ]
