# Generated by Django 4.1.7 on 2023-03-16 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userAuth', '0008_alter_userdetails_company_childuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('adress', models.TextField()),
                ('phone', models.IntegerField()),
                ('company', models.TextField(unique=True)),
                ('companyType', models.CharField(max_length=20)),
                ('accountPermisions', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='ChildUser',
            new_name='CompanyEmployer',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.AlterField(
            model_name='companyemployer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.company'),
        ),
    ]
